version: '3.8'

services:
  valoracion-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./Models:/app/Models
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HOST=0.0.0.0